# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_auto_20171124_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votos',
            name='voted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votos.Candidato'),
        ),
    ]
